import { readFileSync } from 'node:fs';
import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { beforeAll, beforeEach, afterAll, describe, expect, it, vi } from 'vitest';
import { assertFails, assertSucceeds, initializeTestEnvironment, type RulesTestEnvironment } from '@firebase/rules-unit-testing';
import { initializeApp, deleteApp, type FirebaseApp } from 'firebase/app';
import { getFirestore, connectFirestoreEmulator, doc, getDoc, getDocs, collection, setDoc, updateDoc, type Firestore as ClientFirestore } from 'firebase/firestore';
import { Firestore, Timestamp, GeoPoint } from 'firebase-admin/firestore';
import { loadEmulatorRules } from '../../scripts/swim-resources/lib/emulator-rules.mjs';
import { reconcileBundle } from '../../scripts/swim-resources/lib/evidence-reconciler.mjs';
import { updateReviewQuestions } from '../../scripts/swim-resources/lib/review-questions.mjs';
import { exportDataset, restoreArchive } from '../../scripts/swim-resources/lib/dataset-archive.mjs';
import { hashBytes, privateWrite } from '../../scripts/swim-resources/lib/evidence-archive.mjs';
import { evidenceKey } from '../../src/features/swim-resources/lib/domain/evidence';
import { readViewerDocument, readViewerPage } from '../../src/features/swim-resources/lib/services/data-viewer';
const runtime = vi.hoisted(() => ({ db: null as unknown as ClientFirestore, user: { uid: 'coach', email: 'coach@velocity-swimming.com', emailVerified: true } }));
vi.mock('@/features/swim-resources/lib/firebase', () => ({ get db() { return runtime.db; }, auth: { get currentUser() { return runtime.user; } }, FIREBASE_PROJECT_ID: 'demo-cutter-coach', FIRESTORE_DATABASE_ID: 'velocity-v2' }));
import { previewImportBatch, applyImportBatch, loadImportReceipts, reverseImportChanges } from '../../src/features/swim-resources/lib/services/import-batches';
import { writeWithOrigins } from '../../src/features/swim-resources/lib/services/evidence';
const project = 'demo-cutter-coach', at = '2026-10-07T12:00:00Z', hash = hashBytes(Buffer.from('Synthetic capture'));
let environment: RulesTestEnvironment, admin: Firestore, directory: string;
const apps: FirebaseApp[] = [];
const localClient = (name: string, authenticated: boolean) => {
  const app = initializeApp({ projectId: project, apiKey: 'demo-key' }, name); apps.push(app);
  const db = getFirestore(app, 'velocity-v2');
  connectFirestoreEmulator(db, '127.0.0.1', 8088, authenticated ? { mockUserToken: { sub: 'coach', email: 'coach@velocity-swimming.com', email_verified: true } } : {});
  return db;
};
beforeAll(async () => {
  process.env.FIRESTORE_EMULATOR_HOST = '127.0.0.1:8088';
  environment = await initializeTestEnvironment({ projectId: project, firestore: { host: '127.0.0.1', port: 8088, rules: readFileSync('firestore.rules', 'utf8') }, storage: { host: '127.0.0.1', port: 9199, rules: readFileSync('storage.rules', 'utf8') } });
  await loadEmulatorRules(project, 'velocity-v2');
  admin = new Firestore({ projectId: project, databaseId: 'velocity-v2' });
  runtime.db = localClient('fresh-coach', true);
  await privateWrite('backups/evidence-test-root/.keep', 'synthetic');
  directory = await mkdtemp('backups/evidence-test-root/run-');
});
beforeEach(async () => {
  await fetch(`http://127.0.0.1:8088/emulator/v1/projects/${project}/databases/velocity-v2/documents`, { method: 'DELETE' });
  await admin.doc('sources/official').set({ id: 'official', name: 'Official', reference: 'fixture:current', kind: 'manual', retrieval: 'local', scope: 'Current', intervalDays: 30, enabled: true });
  await admin.doc('sources/official/checks/first').set({ sourceId: 'official', outcome: 'retrieved', revisionId: hash, at });
  await admin.doc('sources/official/revisions/' + hash).set({ hash, storagePath: `evidence/${project}/velocity-v2/official/${hash}` });
});
afterAll(async () => {
  await admin?.terminate(); await environment?.cleanup(); for (const app of apps) await deleteApp(app); if (directory) await rm(directory, { recursive: true, force: true });
});
const batch = (id: string, kind: string, data: Record<string, unknown>) => ({ version: 2, target: { project, database: 'velocity-v2' }, id, collectedAt: at, sources: [{ id: 'official', name: 'Official', kind: 'manual', reference: 'fixture:current', revisionId: hash, checkId: 'first', collectedAt: at, coverage: 'complete', scope: 'Current' }], rows: [{ id: 'row', kind, sourceIds: ['official'], verified: true, data, evidence: [{ sourceId: 'official', revisionId: hash, checkId: 'first', checkedAt: at, fields: Object.keys(data).filter(key => key !== 'id'), context: 'Current', excerpt: 'Synthetic coach-reviewed facts.' }] }], unresolved: [] });
const context = (apply: boolean) => ({ db: admin, project, database: 'velocity-v2', apply, storageOptions: { projectId: project } });
describe('fresh database and evidence privacy', () => {
  it('keeps review questions private through bounded reads, refresh, imports and reversal', async () => {
    await applyImportBatch(await previewImportBatch(batch('question-seed', 'team', { id: 'velocity-swimming', name: 'Velocity Swimming' })), ['row']);
    const targetPath = 'teams/velocity-swimming', key = await evidenceKey(targetPath);
    const manifest = { version: 1, id: 'question-review', target: { project, database: 'velocity-v2' }, updates: [{ targetPath, id: 'website', status: 'open', question: 'Which website is authoritative?', fields: ['website'], evidence: [{ sourceId: 'official', revisionId: hash, checkId: 'first', checkedAt: at, excerpt: 'Synthetic identity has no confirmed website.' }] }] };
    const before = (await exportDataset(admin)).fingerprint;
    await updateReviewQuestions(context(false), manifest, at);
    expect((await exportDataset(admin)).fingerprint).toBe(before);
    await updateReviewQuestions(context(true), manifest, at);
    const fingerprint = (await exportDataset(admin)).fingerprint;
    await readViewerPage('sources');
    await readViewerPage('record_provenance', { field: 'targetCollection', value: 'teams' });
    await readViewerPage('record_provenance', { field: 'targetCollection', value: 'teams' });
    await readViewerDocument('record_provenance/' + key);
    expect((await exportDataset(admin)).fingerprint).toBe(fingerprint);
    const anonymous = localClient('questions-anonymous', false);
    await assertFails(getDoc(doc(anonymous, 'record_provenance/' + key)));
    await assertFails(getDocs(collection(anonymous, 'record_provenance/' + key + '/events')));
    await admin.doc('sources/official/checks/question-second').set({ outcome: 'retrieved', revisionId: hash, at: '2026-10-08T12:00:00Z' });
    const change = batch('question-change', 'team', { id: 'velocity-swimming', name: 'Updated Velocity' });
    change.sources[0].checkId = 'question-second'; change.rows[0].evidence[0].checkId = 'question-second'; change.rows[0].evidence[0].checkedAt = '2026-10-08T12:00:00Z';
    await applyImportBatch(await previewImportBatch(change), ['row']);
    await reverseImportChanges('question-change', ['row']);
    expect((await admin.doc(targetPath).get()).data()?.name).toBe('Velocity Swimming');
    expect((await admin.doc('record_provenance/' + key).get()).data()).toMatchObject({ needsAttention: true, reviewQuestions: [expect.objectContaining({ status: 'open' })] });
  });
  it('enforces named database rules, legacy isolation, no old imports, and read-only viewing', async () => {
    await admin.doc('people/test').set({ id: 'test', name: 'Private contact' });
    const anonymous = localClient('fresh-anonymous', false);
    await assertFails(getDoc(doc(anonymous, 'people/test')));
    await assertFails(getDocs(collection(anonymous, 'sources')));
    await assertFails(setDoc(doc(runtime.db, 'results/legacy'), { First: 'Legacy' }));
    const before = (await exportDataset(admin)).fingerprint;
    await readViewerPage('people', {}); await readViewerDocument('people/test'); await readViewerPage('people', {});
    expect((await exportDataset(admin)).fingerprint).toBe(before);
    await expect(previewImportBatch({ version: 1, id: 'old' })).rejects.toThrow('version 2');
    await expect(previewImportBatch({ ...batch('wrong', 'team', { id: 'velocity-swimming', name: 'Velocity Swimming' }), target: { project: 'other', database: 'velocity-v2' } })).rejects.toThrow('matching');
    expect((await getDocs(collection(anonymous, 'public_athletes'))).empty).toBe(true);
    expect((await getDocs(collection(anonymous, 'athletes/test/bests'))).empty).toBe(true);
    const original = new Firestore({ projectId: project });
    await original.doc('test/rollback').set({ original: true });
    expect((await admin.doc('test/rollback').get()).exists).toBe(false);
    await original.doc('test/rollback').delete(); await original.terminate();
  });
  it('keeps archive objects private and immutable, including coaching clients', async () => {
    const path = `evidence/${project}/velocity-v2/official/${hash}`;
    await environment.withSecurityRulesDisabled(async ctx => { await ctx.storage().ref(path).put(Buffer.from('Synthetic capture')); });
    await assertSucceeds(environment.authenticatedContext('coach', { email: 'coach@velocity-swimming.com', email_verified: true }).storage().ref(path).getMetadata());
    await assertFails(environment.unauthenticatedContext().storage().ref(path).getMetadata());
    await assertFails(environment.authenticatedContext('outside', { email: 'outside@example.test', email_verified: true }).storage().ref(path).getMetadata());
    const coach = environment.authenticatedContext('coach', { email: 'coach@velocity-swimming.com', email_verified: true }).storage();
    await assertFails(Promise.resolve(coach.ref(path).put(Buffer.from('replacement')))); await assertFails(coach.ref(path).delete());
    await assertFails(updateDoc(doc(runtime.db, 'sources/official/checks/first'), { at: 'changed' }));
    await assertFails(setDoc(doc(runtime.db, 'public_athletes/test'), { id: 'test', name: { first: 'Test', last: 'Swimmer' }, aliases: [], evidence: { privateEmail: 'secret' } }));
    await assertFails(setDoc(doc(runtime.db, 'athletes/test/bests/100_FR_SCY'), { bestTimeMs: 123, evidence: 'private' }));
    await assertFails(setDoc(doc(runtime.db, 'standards/test'), { cuts: {}, provenance: 'private' }));
  });
  it('reviews population in dependency order, atomically applies evidence, recovers receipts and reverses guarded updates', async () => {
    const dependent = batch('person', 'person', { id: 'coach-person', name: 'Test Coach' });
    expect((await previewImportBatch(dependent)).rows[0].status).toBe('conflict');
    const seed = await previewImportBatch(batch('seed', 'team', { id: 'velocity-swimming', name: 'Velocity Swimming' }));
    await applyImportBatch(seed, ['row']);
    const person = await previewImportBatch(dependent); expect(person.rows[0].status).toBe('add');
    await applyImportBatch(person, ['row']); await applyImportBatch(person, ['row']);
    expect(await loadImportReceipts('person')).toHaveLength(1);
    const prov = await admin.doc('record_provenance/' + await evidenceKey('people/coach-person')).get();
    expect(prov.data()?.origin).toBe('manual'); expect(prov.data()?.lastSuccessfulCheckAt).toBeNull();
    await admin.doc('sources/official/checks/second').set({ outcome: 'retrieved', revisionId: hash, at: '2026-10-08T12:00:00Z' });
    const changed = batch('changed', 'person', { id: 'coach-person', name: 'Updated Coach' });
    changed.sources[0].checkId = 'second'; changed.rows[0].evidence[0].checkId = 'second'; changed.rows[0].evidence[0].checkedAt = '2026-10-08T12:00:00Z';
    await prov.ref.update({ openDisagreements: ['prior-conflict'], needsAttention: true });
    await prov.ref.collection('disagreements').doc('prior-conflict').set({ status: 'open', claims: [{ field: 'name' }] });
    await applyImportBatch(await previewImportBatch(changed), ['row']);
    expect((await prov.ref.collection('disagreements').doc('prior-conflict').get()).data()?.status).toBe('resolved');
    await reverseImportChanges('changed', ['row']); expect((await admin.doc('people/coach-person').get()).data()?.name).toBe('Test Coach');
    expect((await prov.ref.collection('disagreements').doc('prior-conflict').get()).data()?.status).toBe('open');
    expect((await prov.ref.get()).data()?.openDisagreements).toEqual(['prior-conflict']);
    expect((await admin.collection('record_provenance/' + await evidenceKey('people/coach-person') + '/events').get()).size).toBe(3);
    await expect(reverseImportChanges('person', ['row'])).rejects.toThrow('coaching references');
  });
  it('reconciles capture archives, disagreements and receipts idempotently; archive failure preserves facts', async () => {
    await admin.doc('teams/velocity-swimming').set({ id: 'velocity-swimming', name: 'Velocity Swimming' });
    await admin.doc('source_bindings/name').set({ id: 'name', sourceId: 'official', targetPath: 'teams/velocity-swimming', fields: ['name'], context: 'Current', priority: 1 });
    await admin.doc('sources/official').update({ kind: 'website' });
    const file = join(directory, hash); await privateWrite(file, Buffer.from('Synthetic capture'));
    const bundle = { version: 2, target: { project, database: 'velocity-v2' }, captures: [{ sourceId: 'official', checkId: 'collected', at, outcome: 'retrieved', hash, contentType: 'text/plain', file }], observations: [{ targetPath: 'teams/velocity-swimming', claims: { name: 'Verified Velocity' }, evidence: { sourceId: 'official', revisionId: hash, checkId: 'collected', checkedAt: at, fields: ['name'], context: 'Current', excerpt: 'Synthetic name observation' } }] };
    const before = (await exportDataset(admin)).fingerprint;
    expect(await reconcileBundle(context(false), bundle, 'demo-private')).toMatchObject({ changed: 1 }); expect((await exportDataset(admin)).fingerprint).toBe(before);
    expect(await reconcileBundle(context(true), bundle, 'demo-private')).toMatchObject({ changed: 1 });
    expect((await admin.doc('teams/velocity-swimming').get()).data()?.name).toBe('Verified Velocity');
    expect(await reconcileBundle(context(true), bundle, 'demo-private')).toMatchObject({ skipped: 1, changed: 0 });
    const receipts = await admin.collectionGroup('changes').get(); expect(receipts.size).toBe(1);
    await reverseImportChanges(receipts.docs[0].ref.parent.parent!.id, [receipts.docs[0].id]);
    expect((await admin.doc('teams/velocity-swimming').get()).data()?.name).toBe('Velocity Swimming');
    const previous = (await admin.doc('record_provenance/' + await evidenceKey('teams/velocity-swimming')).get()).data();
    const incomplete = structuredClone(bundle); incomplete.captures[0].checkId = 'incomplete'; incomplete.observations[0].evidence.checkId = 'incomplete'; incomplete.observations[0].claims = { name: 123 as unknown as string };
    expect(await reconcileBundle(context(true), incomplete, 'demo-private')).toMatchObject({ held: 1, changed: 0 });
    const attention = (await admin.doc('record_provenance/' + await evidenceKey('teams/velocity-swimming')).get()).data();
    expect(attention?.failures.official).toBe('Invalid or incomplete verified fields');
    expect(attention?.lastSuccessfulCheckAt).toBe(previous?.lastSuccessfulCheckAt);
    expect((await admin.doc('teams/velocity-swimming').get()).data()?.name).toBe('Velocity Swimming');
    const failed = structuredClone(bundle); failed.captures[0].checkId = 'archive-failed'; failed.observations[0].evidence.checkId = 'archive-failed';
    expect(await reconcileBundle(context(true), failed, 'demo-private', async () => { throw new Error('Synthetic archive failure'); })).toMatchObject({ failures: 1, changed: 0 });
    const provenance = (await admin.doc('record_provenance/' + await evidenceKey('teams/velocity-swimming')).get()).data();
    expect(provenance?.needsAttention).toBe(true); expect(provenance?.failures.official).toBe('Archive unavailable');
    expect((await admin.doc('teams/velocity-swimming').get()).data()?.name).toBe('Velocity Swimming');
  });
  it('invalidates accepted field evidence after manual corrections while preserving the earlier pointers', async () => {
    await applyImportBatch(await previewImportBatch(batch('seed', 'team', { id: 'velocity-swimming', name: 'Velocity Swimming' })), ['row']);
    await applyImportBatch(await previewImportBatch(batch('person', 'person', { id: 'test', name: 'Reviewed contact' })), ['row']);
    const path = 'people/test', previous = (await admin.doc(path).get()).data()!;
    await writeWithOrigins([{ path, after: { ...previous, name: 'Manual correction' }, origin: 'manual' }]);
    const provenance = admin.doc('record_provenance/' + await evidenceKey(path)), summary = (await provenance.get()).data();
    expect(summary?.accepted.name).toBeUndefined(); expect(summary?.requiredFields).toContain('name'); expect(summary?.needsAttention).toBe(true);
    const history = await provenance.collection('events').get();
    expect(history.docs.some(event => event.data().previousEvidence?.name?.checkId === 'first')).toBe(true);
  });
  it('exports every descendant including orphan parents and verifies lossless restoration', async () => {
    await admin.doc('private/parent').set({ at: new Timestamp(10, 456), coordinates: new GeoPoint(47, -122), bytes: Buffer.from('evidence'), reference: admin.doc('sources/official') });
    await admin.doc('private/missing/children/child/deeper/leaf').set({ retained: true });
    const archive = await exportDataset(admin);
    expect(archive.entries.some(e => e.path === 'private/missing/children/child/deeper/leaf')).toBe(true);
    const restored = new Firestore({ projectId: project, databaseId: 'restore-test' });
    await fetch(`http://127.0.0.1:8088/emulator/v1/projects/${project}/databases/restore-test/documents`, { method: 'DELETE' });
    expect(await restoreArchive(restored, archive)).toBe(archive.entries.length);
    expect((await exportDataset(restored)).fingerprint).toBe(archive.fingerprint);
    await expect(restoreArchive(restored, archive)).rejects.toThrow('empty'); await restored.terminate();
  });
});
